server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/jordiny/spring-boot-microservices-store.git
          searchPaths: config-data
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t